---
name: Build

on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
    inputs: {}

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - name: Set up Node
        uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3.0.0
        with:
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
          node-version: "16"

      - name: Build
        run: |
          npm ci
          npm run build
